#!/bin/sh
if [ -z "${DBUS_SESSION_BUS_ADDRESS:-}" ]; then
  exec dbus-run-session -- "$0" "$@"
fi
unset LC_ALL
export LANGUAGE=en
export LC_MESSAGES=C
python3 /usr/share/svent/xfce-panel/prepare-desktop.py --offline
exec /etc/xdg/xfce4/xinitrc "$@"
