#!/bin/sh
if [ -z "${DBUS_SESSION_BUS_ADDRESS:-}" ]; then
  exec dbus-run-session -- "$0" "$@"
fi
unset LC_ALL
export LANGUAGE=en
export LC_MESSAGES=C
export XDG_CURRENT_DESKTOP=XFCE
exec python3 /usr/share/svent/xfce-panel/start-session.py "$@"
